export * from "./hotel.interfaces";
export * from "./rating.interfaces";
export * from "./amenities.interfaces";
export * from "./hotelList.interfaces";
export * from "./allCity.interfaces";
export * from "./memberNavBar.interfaces";
export * from "./rewards.interfaces";
export * from "./aboutUzoData.interfaces";
export * from "./offer.interfaces";
